item {
    id: 1
    name: 'artichoke'
}

item {
    id: 2
    name: 'avocado'
}

item {
    id: 3
    name: 'beetroot'
}

item {
    id: 4
    name: 'broccoli'
}

item {
    id: 5
    name: 'Brussels-sprouts'
}

item {
    id: 6
    name: 'Butternut-squash'
}

item {
    id: 7
    name: 'carrot'
}

item {
    id: 8
    name: 'Cayenne-pepper'
}

item {
    id: 9
    name: 'Celeriac'
}

item {
    id: 10
    name: 'celery'
}

item {
    id: 11
    name: 'Chick-pea'
}

item {
    id: 12
    name: 'eggplant'
}

item {
    id: 13
    name: 'flat-beans'
}

item {
    id: 14
    name: 'garlic'
}

item {
    id: 15
    name: 'ginger'
}

item {
    id: 16
    name: 'Green-beans'
}

item {
    id: 17
    name: 'Green-cabbage'
}

item {
    id: 18
    name: 'Honeydew'
}

item {
    id: 19
    name: 'iceberg-lettuce'
}

item {
    id: 20
    name: 'Jalapeno-pepper'
}

item {
    id: 21
    name: 'ladies-fingers'
}

item {
    id: 22
    name: 'leeks'
}

item {
    id: 23
    name: 'lemon'
}

item {
    id: 24
    name: 'Parsley'
}

item {
    id: 25
    name: 'peas'
}

item {
    id: 26
    name: 'potato'
}

item {
    id: 27
    name: 'radish'
}

item {
    id: 28
    name: 'Sweet-corn'
}

item {
    id: 29
    name: 'tomato'
}

item {
    id: 30
    name: 'Watermelon'
}
